config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }

  scope '(:locale)', locale: /fr|en/ do
    get 'welcome/index'
    get '/rules', to: 'welcome#rules'

    resources :users, only: [:index, :show, :edit, :update]
    resources :competitions do
      resources :tracks, only: [:destroy, :edit, :update]
      resources :subscriptions, only: [:new, :edit, :update, :create, :destroy]
      get 'event', to: 'competitions#event'
    end

    resources :notification_settings, only: [:update]

    %w( 404 422 500 ).each do |code|
      get code, to: "errors#show", code: code
    end

    root 'welcome#index'

    require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

end

app/models/competition.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: competitions
#
#  id                          :integer          not null, primary key
#  name                        :string
#  start_date                  :date
#  end_date                    :date
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  finished                    :boolean          default(FALSE), not null
#  published                   :boolean          default(FALSE), not null
#  start_registration          :datetime
#  end_registration            :datetime
#  author_id                   :integer
#  description                 :text
#  video                       :string
#  start_city_id               :integer
#  end_city_id                 :integer
#  default_registration_status :integer          default("pending"), not null
#
# Indexes
#
#  index_competitions_on_start_city_id_and_end_city_id  (start_city_id,end_city_id)
#
# Foreign Keys
#
#  fk_rails_...  (author_id => users.id)
#  fk_rails_...  (end_city_id => cities.id)
#  fk_rails_...  (start_city_id => cities.id)
#

class Competition < ApplicationRecord
  scope :published, -> { where(published: true) }
  scope :finished, -> { where(finished: true).most_recent_first }
  scope :not_finished, -> { where(finished: false).most_recent_last }
  scope :most_recent_first, -> { order(start_date: :desc) }
  scope :most_recent_last, -> { order(:start_date) }

  has_many :subscriptions, dependent: :destroy
  has_many :pending_subscriptions, -> { pending.order(:created_at) },
           class_name: "Subscription", inverse_of: :competition
  has_many :users, through: :subscriptions
  has_many :accepted_users, -> { merge(Subscription.accepted) },
           through: :subscriptions,
           source: :user
  has_many :pending_users, -> { merge(Subscription.pending) },
           through: :subscriptions,
           source: :user
  has_many :refused_users, -> { merge(Subscription.refused) },
           through: :subscriptions,
           source: :user

  has_many :tracks, -> { order :start_time }, dependent: :destroy,
                                              inverse_of: :competition

  has_many :ranks, as: :race, dependent: :destroy, inverse_of: :race
  has_many :t_ranks, through: :tracks, source: :ranks

  belongs_to :start_city, class_name: "City", foreign_key: "start_city_id",
                          inverse_of: :start_of_competitions
  belongs_to :end_city, class_name: "City", foreign_key: "end_city_id",
                        inverse_of: :end_of_competitions

  has_many :tracks_start_cities, through: :tracks, source: :start_city
  has_many :tracks_end_cities, through: :tracks, source: :end_city

  belongs_to :author, class_name: "User", inverse_of: :creations

  enum default_registration_status: { pending: 0, accepted: 1 },
       _prefix: :default

  def to_s
    name
  end

  def locations
    "#{start_city.locality} (#{start_city.country_short}) – #{end_city.locality} (#{end_city.country_short})"
  end

  def route
    rte = "#{start_city.locality} (#{start_city.country_short}) – "
    tracks.each do |t|
      next if t.end_city.locality == end_city.locality

      rte += "#{t.end_city.locality} (#{t.end_city.country_short}) – "
    end
    rte += "#{end_city.locality} (#{end_city.country_short})"
  end

  def multiple_tracks?
    tracks.size > 1
  end

  def just_published?
    previous_changes["published"]&.last
  end

  def enough_changes?
    previous_changes.except("created_at", "updated_at", "finished", "published",
                            "start_registration", "end_registration", "author_id",
                            "default_registration_status").present?
  end

  def registrations_open?
    return false if finished || start_registration.blank?

    if end_registration
      Time.current.between?(start_registration, end_registration)
    elsif start_date
      Time.current.between?(start_registration, start_date - 1.day)
    else
      false
    end
  end

  def after_registrations?
    if start_registration && end_registration
      Time.current > end_registration && Time.current < start_date
    else
      false
    end
  end

  def before_registrations?
    if start_registration
      Time.current < start_registration
    else
      false
    end
  end

  def status
    return :finished if finished
    return :open if registrations_open?

    :closed
  end

  def self.open_for_registration
    all.select(&:registrations_open?)
  end

  def self.not_open_for_registration
    all.reject(&:registrations_open?)
  end

  # To render directions on maps
  def as_json(*_args)
    slice(:id, :name).merge(start_city: start_city.slice(:lat, :lng, :name),
                            end_city: end_city.slice(:lat, :lng, :name),
                            tracks: tracks.map do |t|
                              { end_city: t.end_city.slice(:name) }
                            end)
  end

  def ical_event
    require "icalendar"

    cal = Icalendar::Calendar.new

    cal.event do |e|
      e.dtstart     = Icalendar::Values::Date.new(start_date)
      e.dtend       = Icalendar::Values::Date.new(end_date)
      e.summary     = name
      e.location    = "#{start_city.locality} (#{start_city.country_short})"
      e.description = "#{name}\n#{route}\n\n#{description}"
      e.url         = "https://www.somewherexpress.com/competitions/#{id}"
      e.status      = "CONFIRMED"
    end

    cal.to_ical
  end
end

app/controllers/competitions_controller.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: competitions
#
#  id                          :integer          not null, primary key
#  name                        :string
#  start_date                  :date
#  end_date                    :date
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  finished                    :boolean          default(FALSE), not null
#  published                   :boolean          default(FALSE), not null
#  start_registration          :datetime
#  end_registration            :datetime
#  author_id                   :integer
#  description                 :text
#  video                       :string
#  start_city_id               :integer
#  end_city_id                 :integer
#  default_registration_status :integer          default("pending"), not null
#
# Indexes
#
#  index_competitions_on_start_city_id_and_end_city_id  (start_city_id,end_city_id)
#
# Foreign Keys
#
#  fk_rails_...  (author_id => users.id)
#  fk_rails_...  (end_city_id => cities.id)
#  fk_rails_...  (start_city_id => cities.id)
#

class CompetitionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_competition, only: [:edit, :update, :destroy]
  before_action :set_preloaded_competition, only: [:show]

  def index
    @competitions = policy_scope(Competition)
                    .published
                    .most_recent_first
                    .preload(:start_city, :end_city, :accepted_users,
                             :pending_users, :refused_users,
                             tracks: [:start_city, :end_city],
                             subscriptions: :user)

    @markers = Marker.for_all_relevant_cities
  end

  def show
    authorize @competition

    @form = Competition::Contract::Update.new(@competition) if policy(@competition).update?
  end

  def event
    @competition = Competition.find(params[:competition_id])
    authorize @competition, :will_participate?

    respond_to do |format|
      format.ics { render text: @competition.ical_event, layout: false }
    end
  end

  def new
    authorize Competition, :create?

    @form = Competition::Contract::Create.new(Competition.new).prepopulate!
  end

  # This endpoint is only used on update errors
  def edit
    authorize @competition, :update?

    @form = Competition::Contract::Update.new(@competition)
  end

  def create
    operation = Competition::Create.call(params.merge(current_user: current_user))

    @form = operation.form

    if @form.valid?
      redirect_to operation.model
    else
      @form.prepopulate!
      render action: :new
    end
  end

  def update
    operation = Competition::Update.call(params.merge(current_user: current_user))

    @form = operation.form

    if @form.valid?
      redirect_to operation.model
    else
      render action: :edit
    end
  end

  def destroy
    authorize @competition

    @competition.destroy
    redirect_to competitions_path, notice: "Competition was successfully deleted."
  end

  private

    def set_competition
      @competition = Competition.find(params[:id])
    end

    def set_preloaded_competition
      @competition = Competition.preload(:start_city, :end_city,
                                         tracks: [:start_city, :end_city,
                                                  ranks: :user],
                                         ranks: :user)
                                .find(params[:id])
    end
end

app/helpers/competitions_helper.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: competitions
#
#  id                          :integer          not null, primary key
#  name                        :string
#  start_date                  :date
#  end_date                    :date
#  created_at                  :datetime         not null
#  updated_at                  :datetime         not null
#  finished                    :boolean          default(FALSE), not null
#  published                   :boolean          default(FALSE), not null
#  start_registration          :datetime
#  end_registration            :datetime
#  author_id                   :integer
#  description                 :text
#  default_registration_status :string           default("pending"), not null
#  video                       :string
#

module CompetitionsHelper
  def result(rank)
    if rank.try(:result) == 1
      '<span class="trophies"><i class="fa fa-trophy"></i></span>'.html_safe
    elsif rank.try(:dsq)
      "DSQ"
    else
      rank.try(:result)
    end
  end

  def track_result(rank)
    if rank.try(:result) == 1
      '<span class="medals"><i class="icomoon icon-medal"></i></span>'.html_safe
    else
      rank.try(:result)
    end
  end

  def place(rank)
    if rank&.dsq
      "DSQ"
    elsif rank
      case I18n.locale
      when :fr
        "#{rank.result}<sup>#{rank.result == 1 ? 're' : 'e'}</sup> place".html_safe
      else
        "#{rank.result}<sup>#{rank.result.ordinal}</sup> place".html_safe
      end
    else
      ""
    end
  end

  def ribon(status)
    case status
    when :open
      "<div class='ribbon-green'>#{t('competitions.open', count: 1)}</div>".html_safe
    when :finished
      "<div class='ribbon-gray'>#{t('competitions.finished')}</div>".html_safe
    when :closed
      "<div class='ribbon-blue'>#{t('competitions.closed', count: 1)}</div>".html_safe
    end
  end
end

app/views/competitions/_accepted_user.html.erb
<li class="list-group-item flex-container">
  <%= render 'subscriptions/user_registred', user: user %>
  <div class="flex-item">
    <i class="fa fa-check text-success cursor-default flex-item" data-toggle="tooltip" data-placement="bottom" title="<%= t('subscriptions.accepted_short') %>"></i>
  </div>
</li>

app/views/competitions/_card.html.erb
<div class="card">
  <div class="card-image">
    <div class="bg-image-competition" style="background-image: url(<%= competition.end_city.picture %>);">
    </div>
  </div>
  <div id="panel-<%= competition.id %>" class="card-body">
    <div class="ribbon-wrapper"><%= ribon(competition.status) %></div>
    <div class="list-body">
      <div class="left-of-ribbon">
        <h4><%= link_to competition, competition %></h4>
        <p class="text-uppercase small"><%= competition.route %></p>
        <p class="text-uppercase text-muted small"><%= date_format(competition.start_date) %> – <%= date_format(competition.end_date) %></p>
      </div>

      <%# this div is refreshed on subscriptions create/update: %>
      <div id="competition-<%= competition.id %>-dynamic">
        <%= render "competitions/dynamic", competition: competition %>
      </div>
    </div>
  </div>
</div>

app/views/competitions/_city_form.html.erb
<%= city.input :name, label: label %>
<%= city.input :locality, as: :hidden %>
<%= city.input :country_short, as: :hidden %>
<%= city.input :picture, as: :hidden %>

app/views/competitions/_destroy_form.html.erb
<% if policy(competition).destroy? %>
  <div class="panel panel-danger marged-mini">
    <div class="panel-heading">
      <strong><%= t('competitions.show.destroy.panel') %></strong>
    </div>
    <div class="panel-body">
      <p><strong><%= t('competitions.show.destroy.title') %></strong></p>
      <%= link_to t('competitions.show.destroy.title'), competition_path(competition), method: 'delete', class: "btn btn-danger pull-right" %>
      <p><%= t('competitions.show.destroy.text') %></p>
    </div>
  </div>
<% end %>

app/views/competitions/_final_ranks.html.erb
<%- (ranks.reject { |r| r.result == 0 }.sort_by { |r| [r.dsq, r.result] } +
     ranks.select { |r| r.result == 0 }).each do |rank| -%>
  <tr>
    <td class="text-center"><%= result(rank) %></td>
    <td class="text-center">
      <%= render 'users/avatar_small', user: rank.user %>
    </td>
    <td class="text-uppercase"><%= link_to rank.user, rank.user %></td>
    <td class="text-right text-uppercase"><%= rank.points %> <%= t('ranks.params.points') %></td>
  </tr>
<%- end -%>

app/views/competitions/_form.html.erb
<%= simple_form_for form do |f| %>
  <%= f.error_notification %>

  <!-- GENERAL INFORMATIONS -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong><%= t('.general.title') %></strong>
    </div>
    <div class="panel-body">
      <%= f.input :name, label: t('competitions.params.name') %>
      <div class="row">
        <div class="col-xs-6">
          <%= f.simple_fields_for :start_city do |c| %>
            <%= render "city_form", city: c, label: t('competitions.params.start_location') %>
          <% end %>
        </div>
        <div class="col-xs-6">
          <%= f.simple_fields_for :end_city do |c| %>
            <%= render "city_form", city: c, label: t('competitions.params.end_location') %>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-6">
          <%= f.label :start_date, t('competitions.params.start_date') %>
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            <%= f.input :start_date, as: :string, label: false, input_html: { type: "date", class: "datepicker" } %>
          </div>
        </div>
        <div class="col-xs-6">
          <%= f.label :end_date, t('competitions.params.end_date') %>
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            <%= f.input :end_date, as: :string, label: false, input_html: { type: "date", class: "datepicker" } %>
          </div>
        </div>
        <div class="col-xs-12 padded-mini-top">
          <%= f.input :description, input_html: { rows: 6 } %>
        </div>
      </div>
    </div>
  </div>
  <!-- END GENERAL INFORMATIONS -->

  <!-- TRACKS -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong class="text-capitalize"><%= t('activerecord.models.track', count: 2) %></strong>
    </div>
  </div>
  <%= f.simple_fields_for :tracks do |t| %>
    <%= t.error_notification %>
    <div class="row tracks_form">
      <div class="col-xs-10 col-sm-11">
        <div class="panel panel-default">
          <div class="row panel-body">
            <div class="col-xs-6">
              <%= t.simple_fields_for :start_city, t.object.start_city do |c| %>
                <%= render "city_form", city: c, label: t('tracks.params.start_location') %>
              <% end %>
            </div>
            <div class="col-xs-6">
              <%= t.simple_fields_for :end_city, t.object.end_city do |c| %>
                <%= render "city_form", city: c, label: t('tracks.params.end_location') %>
              <% end %>
            </div>

            <div class="col-xs-12">
              <%= f.label :start_time, t('tracks.params.start_time') %>
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                <%= t.input :start_time, label: false, as: :string, input_html: { class: "datetime_picker", value: datetime_value(t.object.start_time) } %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-2 col-sm-1 padded-mini">
        <% if t.object.new_record? %>
          <%= link_to '#', remote: true, class: 'destroy_track' do %>
            <i class="fa fa-minus-circle" data-toggle="tooltip" data-placement="bottom" title="<%= t('.tracks.remove_track') %>"></i>
          <% end %>
        <% else %>
          <%= link_to competition_track_path(form, t.object), method: :delete, remote: true, data: { confirm: t('.delete.message') }, class: 'destroy_track' do %>
            <i class="fa fa-minus-circle" data-toggle="tooltip" data-placement="bottom" title="<%= t('.tracks.remove_track') %>"></i>
          <% end %>
          <%= t.input :id, as: :hidden %>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="text-center padded-mini-bottom">
    <%= link_to '#', remote: true, class: "add_track" do %>
      <i class="fa fa-plus-circle"></i> <span><%= t('.tracks.add_track') %></span>
    <% end %>
  </div>
  <!-- TRACKS -->

  <!-- SETTINGS -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong><%= t('.rules.title') %></strong>
    </div>
    <div class="panel-body">
      <div class="row padded-mini">
        <div class="col-xs-6">
          <%= f.label :start_registration, t('competitions.params.start_registration') %>
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            <%= f.input :start_registration, as: :string, label: false, input_html: { class: "datetime_picker", value: datetime_value(f.object.start_registration) } %>
          </div>
        </div>
        <div class="col-xs-6">
          <%= f.label :end_registration, t('competitions.params.end_registration') %>
          <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
            <%= f.input :end_registration, as: :string, label: false, input_html: { class: "datetime_picker", value: datetime_value(f.object.end_registration) } %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-12 col-md-8">
          <strong><%= t('.rules.default.question') %></strong>
          <%= f.hint t('.rules.default.hint') %>
        </div>
        <div class="col-xs-12 col-md-4 text-right-center">
          <%= f.collection_radio_buttons :default_registration_status, [["accepted", "check text-success"] ,["pending", "refresh text-warning"]], :first, :last, checked: f.object.default_registration_status do |b| %>
            <% b.label(class: "marged-micro-sides") {"<span class='marged-micro-sides'><i class='fa fa-#{ b.text }'></i> #{t(".rules.default.#{b.value}")}</span>".html_safe + b.radio_button } %>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-9">
          <strong><%= t('.rules.published.question') %></strong>
          <%= f.hint t('.rules.published.hint') %>
        </div>
        <div class="col-xs-3">
          <%= f.input_field :published, as: :boolean, boolean_style: :inline, class: "cmn-toggle cmn-toggle-round" %>
          <label for="competition_published"></label>
        </div>
      </div>

      <div class="row">
        <div class="col-xs-9">
          <strong><%= t('.rules.finished.question') %></strong>
          <%= f.hint t('.rules.finished.hint') %>
        </div>
        <div class="col-xs-3">
          <%= f.input_field :finished, as: :boolean, boolean_style: :inline, class: "cmn-toggle cmn-toggle-round" %>
          <label for="competition_finished"></label>
        </div>
      </div>
    </div>
  </div>
  <!-- SETTINGS -->

  <!-- SOUVENIRS -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <strong>Souvenirs</strong>
    </div>

    <div class="panel-body">
      <%= f.input :video, placeholder: "https://www.youtube.com/embed/your-youtube-id" %>
    </div>
  </div>
  <!-- SOUVENIRS -->

  <%= f.button :submit, class: "btn btn-primary" %> <%= link_to t('cancel'), :back, class: "btn" %>
<% end %>

app/views/competitions/_map.html.erb
<div id="map" style="width: 100%; height: 550px; max-height: 90vh;"></div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    $(document).on('ready', function() {
      mapWithDirectionsAndMarkers(<%= raw competitions.to_json %>, <%= raw markers.to_json %>)
    })
  <% end %>
<% end %>

app/views/competitions/_mono_track.html.erb
<!-- START FINAL RANKING -->
<div id="track-<%= competition.tracks.first.id %>-result" class="panel panel-default">
  <div class="panel-heading">
    <strong>
      <%= t('competitions.show.final_ranking') %>
      <!-- EDIT RESULTS -->
      <% if policy(competition).update? %>
        <small><%= link_to t('competitions.edit_results'), edit_competition_track_path(competition, competition.tracks.first) %></small>
      <% end %>
      <!-- END EDIT RESULTS -->
    </strong>
  </div>

  <table class="table">
    <tbody>
      <% if competition.ranks.reject { |r| r.result == 0 }.any? %>
        <% (competition.ranks.reject { |r| r.result == 0 }.sort_by { |r| [r.dsq, r.result] } + competition.ranks.select { |r| r.result == 0 }).each_slice(2).to_a.each do |rank1, rank2| %>
          <tr>
            <td>
              <%= render 'users/avatar_small', user: rank1.user %>
            </td>
            <td class="text-uppercase"><%= link_to rank1.user, rank1.user %></td>
            <td class="text-center"><%= result(rank1) %></td>
            <% if rank2 %>
              <td class="text-right text-uppercase"><%= link_to rank2.user, rank2.user %></td>
              <td class="text-right">
                <%= render 'users/avatar_small', user: rank2.user %>
              </td>
            <% else %>
              <td></td>
              <td></td>
            <% end %>
          </tr>
        <% end %>
      <% else %>
        <%= render 'final_ranks', ranks: competition.ranks %>
      <% end %>
    </tbody>
  </table>
</div>
<!-- END FINAL RANKING -->

app/views/competitions/_participants.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong><%= t('subscriptions.pending_long') %></strong>
  </div>
  <ul id="competition-<%= competition.id%>-pending" class="list-group">
    <% competition.pending_subscriptions.preload(:user).each do |subscription| %>
      <%= render 'competitions/pending_subscription', subscription: subscription %>
    <% end %>
  </ul>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <strong><%= t('subscriptions.accepted_long') %></strong>
  </div>
  <ul id="competition-<%= competition.id%>-accepted" class="list-group">
    <% competition.accepted_users.each do |user| %>
      <%= render 'competitions/accepted_user', user: user %>
    <% end %>
  </ul>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <strong><%= t('subscriptions.refused_long') %></strong>
  </div>
  <ul id="competition-<%= competition.id%>-refused" class="list-group">
    <% competition.refused_users.each do |user| %>
      <%= render 'competitions/refused_user', user: user %>
    <% end %>
  </ul>
</div>

app/views/competitions/_refused_user.html.erb
<li class="list-group-item flex-container">
  <%= render 'subscriptions/user_registred', user: user %>
  <div class="flex-item">
    <i class="fa fa-times text-danger cursor-default flex-item" data-toggle="tooltip" data-placement="bottom" title="<%= t('subscriptions.refused_short') %>"></i>
  </div>
</li>

app/views/competitions/_registrations.html.erb
<% if competition.registrations_open? %>
  <div class="separator padded-micro"></div>
  <p class="text-uppercase small">
    <%= t('competitions.registrations.end', time: distance_of_time_in_words(competition.end_registration || (competition.start_date - 1), Time.current)) %>:
    <%= (datetime_format(competition.end_registration) || datetime_format(competition.start_date - 1)) %>
  </p>
<% elsif competition.before_registrations? %>
  <div class="separator padded-micro"></div>
  <p class="text-uppercase small">
    <%= t('competitions.registrations.start', time: distance_of_time_in_words(competition.start_registration, Time.current)) %>:
    <%= datetime_format(competition.start_registration) %>
  </p>
<% end %>

app/views/competitions/_rules_calendar.html.erb
<div class="marged-mini-bottom text-center">
  <div class="text-left padded-mini padded-mini-sides border-dashed block-center">
    <p>
      <%= link_to competition_event_path(competition, format: :ics) do %>
        <%= image_tag "icon-calendar.svg", width: "20px", height: "20px" %> &nbsp;&nbsp;<%= t("subscriptions.show.dl_calendar") %>
      <% end %>
    </p>
    <p>
      <%= link_to rules_path do %>
        <%= image_tag "rules.svg", width: "20px", height: "20px" %> &nbsp;&nbsp;<%= t("subscriptions.show.read_rules") %>
      <% end %>
    </p>
  </div>
</div>

app/views/competitions/index.html.erb
<%= content_for(:title) do %>
  <%= t('activerecord.models.competition', count: 2).capitalize %>
<% end %>

<%= content_for(:description) do %>
  Toutes les compétitions de SomewherExpress. <%= t('welcome.index.intro') %>
<% end %>


<%= content_for(:og_image) { @competitions.last&.end_city&.picture } %>

<div class="container padded-mini">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="head-icon text-center"><i class="fa fa-map-signs"></i></div>
      <h1><%= t('activerecord.models.competition', count: 2).capitalize %></h1>
      <div class="text-center padded-mini">
        <%= link_to t('.new.title'), new_competition_path, class: "navbar-wagon-button btn", style: "margin-left: 0" if policy(Competition).create? %>
      </div>

      <% @competitions.select { |c| c.status == :open }.each do |competition| %>
        <div class="marged-mini-bottom"><%= render 'card', competition: competition %></div>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="card-deck">
    <% @competitions.select { |c| c.status == :closed }.each do |competition| %>
      <%= render 'card', competition: competition %>
    <% end %>
    <% @competitions.select { |c| c.status == :finished }.each do |competition| %>
      <%= render 'card', competition: competition %>
    <% end %>
  </div>
</div>

<div class="bg-red">
  <div class="container padded-bottom padded-mini-top">
    <h2 class="text-center"><%= t('welcome.index.passed_title') %></h2>
    <%= render 'competitions/map', markers: @markers, competitions: @competitions.select { |c| c.status == :finished } %>
  </div>
</div>

app/views/competitions/new.html.erb
<%= content_for(:title) do %>
  <%= t('.title') %>
<% end %>

<%= content_for(:description) do %>
  Créer une compétition de SomewherExpress. <%= t('welcome.index.intro') %>
<% end %>

<div class="container padded-mini">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <h3><%= t('.title') %></h3>

      <%= render 'form', form: @form %>
    </div>
  </div>
</div>