config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }

  scope '(:locale)', locale: /fr|en/ do
    get 'welcome/index'
    get '/rules', to: 'welcome#rules'

    resources :users, only: [:index, :show, :edit, :update]
    resources :competitions do
      resources :tracks, only: [:destroy, :edit, :update]
      resources :subscriptions, only: [:new, :edit, :update, :create, :destroy]
      get 'event', to: 'competitions#event'
    end

    resources :notification_settings, only: [:update]

    %w( 404 422 500 ).each do |code|
      get code, to: "errors#show", code: code
    end

    root 'welcome#index'

    require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

end

app/views/shared/_favicon.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-194x194.png" sizes="194x194">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="apple-mobile-web-app-title" content="SomewherExpress">
<meta name="application-name" content="SomewherExpress">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/shared/_footer.html.erb
<footer class="bg-dark-grey">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        SOMEWHEREXPRESS 2015 - <%= Time.current.year %>
        <span class="pull-right">
          <%= link_to "https://www.facebook.com/somewherexpress/", class: "white-link" do %>
            <i class="fa fa-facebook boxed"></i>
          <% end %>
        </span>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_home_navbar.html.erb
<nav class="navbar-wagon home">
  <div class="container navbar-wagon-container">

    <%= link_to root_path, class: "white-link hidden-xs" do %>
      <i class="icomoon icon-se_logo navbar-wagon-logo"></i>
    <% end %>

    <div class="navbar-wagon-pusher"></div>

    <%= link_to competitions_path, class: "navbar-wagon-item navbar-wagon-link text-center" do %>
      <span class="visible-xs-block"><i class="fa fa-map-signs"></i></span>
      <%= t('activerecord.models.competition', count: 2).capitalize %>
    <% end %>
    <hr>
    <%= link_to users_path, class: "navbar-wagon-item navbar-wagon-link text-center" do %>
      <span class="visible-xs-block"><i class="icomoon icon-laurel"></i></span>
      Hall of Fame
    <% end %>
    <hr>

    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag current_user.avatar, class: "avatar", data: {toggle: "tooltip", placement: "bottom"}, title: "#{current_user}", alt: "#{current_user.initials}" %> &nbsp;<i class="fa fa-caret-down text-muted"></i>
          </div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-fw fa-home"></i> <%= t('home') %>
              <% end %>
            </li>
            <li>
              <%= link_to current_user do %>
                <i class="fa fa-fw fa-user"></i> <%= t('users.show.profile.title') %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path(current_user) do %>
                <i class="fa fa-fw fa-cogs"></i> <%= t('users.show.profile.settings') %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-fw fa-sign-out"></i> <%= t('devise.sessions.destroy.sign_out', default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to new_user_session_path, class: "navbar-wagon-item navbar-wagon-link text-center" do %>
        <%= t('devise.sessions.new.sign_in') %>
      <% end %>
      <%= link_to new_user_registration_path, class: "navbar-wagon-item navbar-wagon-button btn" do %>
        <%= t('devise.registrations.new.sign_up') %>
      <% end %>
    <% end %>
    <hr>
    <% if params[:locale] == 'en' %>
      <%= link_to "FR", url_for( locale: 'fr' ), class: "navbar-wagon-item navbar-wagon-link text-center" %>
    <% else %>
      <%= link_to "EN", url_for( locale: 'en' ), class: "navbar-wagon-item navbar-wagon-link text-center" %>
    <% end %>
  </div>
</nav>

app/views/shared/_meta_tags.html.erb
<!-- Open Graph data -->
<meta property="og:title" content="<%= yield(:title) || 'SomewherExpress' %>" />
<meta property="og:type" content="article" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= yield(:og_image) || '' %>" />
<meta property="og:description" content="<%= (yield(:description) || '').squish %>" />
<meta property="og:site_name" content="SomewherExpress" />

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <%= link_to root_path, class: "white-link" do %>
      <i class="icomoon icon-se_logo navbar-wagon-logo"></i>
    <% end %>

    <div class="navbar-wagon-pusher"></div>

    <%= link_to competitions_path, class: "navbar-wagon-item navbar-wagon-link text-center" do %>
      <span class="visible-xs-block"><i class="fa fa-map-signs"></i></span>
      <%= t('activerecord.models.competition', count: 2).capitalize %>
    <% end %>
    <hr>
    <%= link_to users_path, class: "navbar-wagon-item navbar-wagon-link text-center" do %>
      <span class="visible-xs-block"><i class="icomoon icon-laurel"></i></span>
      Hall of Fame
    <% end %>
    <hr>

    <% if user_signed_in? %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <div class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag current_user.avatar, class: "avatar", data: {toggle: "tooltip", placement: "bottom"}, title: "#{current_user}", alt: "#{current_user.initials}" %> &nbsp;<i class="fa fa-caret-down text-muted"></i>
          </div>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-fw fa-home"></i> <%= t('home') %>
              <% end %>
            </li>
            <li>
              <%= link_to current_user do %>
                <i class="fa fa-fw fa-user"></i> <%= t('users.show.profile.title') %>
              <% end %>
            </li>
            <li>
              <%= link_to edit_user_registration_path(current_user) do %>
                <i class="fa fa-fw fa-cogs"></i> <%= t('users.show.profile.settings') %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-fw fa-sign-out"></i> <%= t('devise.sessions.destroy.sign_out', default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <hr>
    <% else %>
      <%= link_to new_user_session_path, class: "navbar-wagon-item navbar-wagon-link text-center" do %>
        <%= t('devise.sessions.new.sign_in') %>
      <% end %>
      <%= link_to new_user_registration_path, class: "navbar-wagon-item navbar-wagon-button btn" do %>
        <%= t('devise.registrations.new.sign_up') %>
      <% end %>
      <hr class="hidden-xs">
    <% end %>
    <% if params[:locale] == 'en' %>
      <%= link_to "FR", url_for( locale: 'fr' ), class: "navbar-wagon-item navbar-wagon-link text-center" %>
    <% else %>
      <%= link_to "EN", url_for( locale: 'en' ), class: "navbar-wagon-item navbar-wagon-link text-center" %>
    <% end %>
  </div>
</nav>

app/views/shared/_notices.html.erb
<div id="alerts-bar">
  <% if notice %>
    <div class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>
  <% if alert %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
  <% end %>
</div>