config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }

  scope '(:locale)', locale: /fr|en/ do
    get 'welcome/index'
    get '/rules', to: 'welcome#rules'

    resources :users, only: [:index, :show, :edit, :update]
    resources :competitions do
      resources :tracks, only: [:destroy, :edit, :update]
      resources :subscriptions, only: [:new, :edit, :update, :create, :destroy]
      get 'event', to: 'competitions#event'
    end

    resources :notification_settings, only: [:update]

    %w( 404 422 500 ).each do |code|
      get code, to: "errors#show", code: code
    end

    root 'welcome#index'

    require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

end

app/controllers/welcome_controller.rb
# frozen_string_literal: true
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @markers = Marker.for_all_relevant_cities
    @open_competitions = Competition.published.not_finished.open_for_registration
    @closed_competitions = Competition.published.not_finished.not_open_for_registration
    @past_competitions = Competition.published.finished
                                    .preload(:start_city, :end_city,
                                             tracks: :end_city)

    if user_signed_in?
      render "dashboard"
    else
      @members = User.with_competitions.left_outer_joins(:badges)
                     .order("count(badges) desc").group("users.id")

      @hof_users = User.hall_of_fame
                       .limit(5)
                       .preload(:competition_victories, :badges,
                                track_victories: [:start_city, :end_city])
      render "index", layout: "home"
    end
  end

  def rules; end
end

app/views/welcome/_map_box.html.erb
<div class="map_box">
  <div>
    <%= image_tag city.picture, width: "150px" %>
  </div>
  <strong><%= city.locality %></strong><br>

  <% city.end_of_tracks.select { |tr| tr.competition.finished }.each do |track| %>
    <%= link_to track.competition, track.competition %>
    <div>
      <span class="medals-small"><i class="icomoon icon-medal"></i></span> <%= track.ranks.select { |r| r.result == 1 }.map { |r| r.user.first_name if r }.join(' & ') %>
    </div>
  <% end %>

  <% if city.end_of_tracks.empty? %>
    <% city.start_of_competitions.finished.distinct.each do |competition| %>
      <%= link_to competition, competition %><br>
    <% end %>
    <% city.end_of_competitions.finished.distinct.each do |competition| %>
      <%= link_to competition, competition %><br>
    <% end %>
    <% # need start_of_tracks as well if it ever happens %>
  <% end %>
</div>

app/views/welcome/dashboard.html.erb
<%= content_for(:title) do %>
  SomewherExpress
<% end %>

<%= content_for(:description) do %>
  <%= t('welcome.index.intro') %>
<% end %>

<div class="dashboard container padded-mini">
  <div class="row">
    <div class="col-sm-5 col-md-4 col-lg-3">
      <div class="panel panel-default bio-panel">
        <div class="cover-image-mini">
        </div>
        <div class="profile-pic">
          <%= link_to current_user do %>
            <%= image_tag current_user.avatar, class: "avatar-ultra", alt: current_user.initials %>
          <% end %>
          <% if current_user.founder_badge %>
            <%= image_tag current_user.founder_badge.picture, class: "avatar-badge", alt: "", data: { toggle: "tooltip", placement: "bottom" }, title: "#{current_user.founder_badge.description}", style: "margin-top: 3px;" %>
          <% end %>
        </div>
        <div class="padded-mini text-center">
          <h4><%= link_to current_user, current_user %></h4>
          <div>
            <% current_user.competition_victories.each do |competition| %>
              <%= link_to competition do %>
                <span class="trophies"><i class="fa fa-trophy" data-toggle="tooltip" data-placement="bottom" title="<%= competition %>"></i></span>
              <% end %>
            <% end %>
            <% current_user.track_victories.each do |track| %>
              <%= link_to competition_path(track.competition, anchor: "track-#{track.id}-result") do %>
                <span class="medals"><i class="icomoon icon-medal" data-toggle="tooltip" data-placement="bottom" title="<%= track %>"></i></span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <% if policy(Competition).create? %>
        <div class="text-center padded-mini-bottom">
          <%= link_to t('competitions.new.title'), new_competition_path, class: "navbar-wagon-button btn", style: "margin-left: 0" %>
        </div>
      <% end %>
    </div>
    <div class="col-sm-7 col-md-8 col-lg-9">

      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#open" aria-controls="open" role="tab" data-toggle="tab"><i class="fa fa-bullhorn fa-fw"></i> <%= t('welcome.index.future_title') %></a></li>

        <% if current_user.creations.not_finished.any? %>
          <li role="presentation">
            <a href="#mines" aria-controls="mines" role="tab" data-toggle="tab">
              <i class="fa fa-dashboard fa-fw"></i>
              <%= t('.creations_title') %>
              <% if current_user.pending_registrations_for_creations > 0 %>
                <span class="badge badge-red registrations-alert"><%= current_user.pending_registrations_for_creations %></span>
              <% end %>
            </a>
          </li>
        <% end %>

        <% if policy(current_user).update? %>
          <div class="pull-right marged-micro visible-lg-block <%= 'visible-md-block' unless current_user.creations.not_finished.any? %>">
            <%= link_to edit_user_path(current_user), class: "btn btn-xs btn-default" do %>
              <i class="fa fa-pencil"></i> <%= t('users.edit.title') %>
            <% end %>
          </div>
        <% end %>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="open">
          <div class="panel panel-default marged-mini">
            <div class="panel-heading">
              <strong><%= t('welcome.index.open_title') %></strong>
            </div>
            <% if @open_competitions.any? %>
              <ul class="list-group">
                <% @open_competitions.each do |competition| %>
                  <%= render 'competitions/card', competition: competition %>
                <% end %>
              </ul>
            <% else %>
              <div class="text-muted padded-mini-full"><em><%= t('competitions.zero') %></em></div>
            <% end %>
          </div>
          <div class="panel panel-default marged-mini">
            <div class="panel-heading">
              <strong><%= t('welcome.index.closed_title') %></strong>
            </div>
            <% if @closed_competitions.any? %>
              <ul class="list-group">
                <% @closed_competitions.each do |competition| %>
                  <%= render 'competitions/card', competition: competition %>
                <% end %>
              </ul>
            <% else %>
              <div class="text-muted padded-mini-full"><em><%= t('competitions.zero') %></em></div>
            <% end %>
          </div>
        </div>

        <% if current_user.creations.not_finished.any? %>
          <div role="tabpanel" class="tab-pane" id="mines">
            <% current_user.creations.not_finished.preload(:subscriptions, :users).each do |competition| %>
              <div class="panel panel-default marged-mini">
                <div class="panel-heading">
                  <strong><i class="fa fa-map-signs"></i> <%= competition %></strong>
                </div>
                <ul class="list-group">
                  <li class="list-group-item">
                    <h4><%= link_to competition, competition %></h4>
                    <p class="text-uppercase small"><%= competition.route %></p>
                    <p class="text-uppercase text-muted small"><%= date_format(competition.start_date) %> – <%= date_format(competition.end_date) %></p>
                  </li>
                </ul>
                <ul id="competition-<%= competition.id%>-pending" class="list-group">
                  <% competition.pending_subscriptions.preload(:user).each do |subscription| %>
                    <%= render 'competitions/pending_subscription', subscription: subscription %>
                  <% end %>
                </ul>
                <ul id="competition-<%= competition.id%>-accepted" class="list-group">
                  <% competition.accepted_users.each do |user| %>
                    <%= render 'competitions/accepted_user', user: user %>
                  <% end %>
                </ul>
                <ul id="competition-<%= competition.id%>-refused" class="list-group">
                  <% competition.refused_users.each do |user| %>
                    <%= render 'competitions/refused_user', user: user %>
                  <% end %>
                </ul>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<%= content_for(:title) do %>
  SomewherExpress
<% end %>

<%= content_for(:description) do %>
  <%= t('welcome.index.intro') %>
<% end %>

<%= content_for(:og_image) { "https://www.somewherexpress.com/master_og_image.jpg" } %>

<div class="welcome">
  <div class="bg-welcome">
    <%= render 'shared/home_navbar' %>
    <div class="container padded intro">
      <div class="row">
        <div class="col-xs-12 col-lg-10 col-lg-offset-1 text-center">
          <div class="lead">
            <%= t('.intro') %>
          </div>
          <div class="users">
            <% @members.each do |user| %>
              <div class="marged-micro-bottom" style="display: inline-block;"><%= render 'users/avatar_medium', user: user %></div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <% if @open_competitions.any? || @closed_competitions.any? %>
  <div class="bg-welcome">
    <div class="container padded-bottom padded-mini-top">
      <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
          <% if @open_competitions.any? %>
            <h2 class="text-center"><%= t('.open_title') %></h2>
            <% @open_competitions.each do |competition| %>
              <div class="marged-mini-bottom"><%= render 'competitions/card', competition: competition %></div>
            <% end %>
          <% end %>

          <% if @closed_competitions.any? %>
            <h2 class="text-center"><%= t('.closed_title') %></h2>
            <% @closed_competitions.each do |competition| %>
              <div class="marged-mini-bottom"><%= render 'competitions/card', competition: competition %></div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>

  <div class="bg-welcome">
    <div class="container padded-bottom padded-mini-top">
      <h2 class="text-center"><%= t('.passed_title') %></h2>
      <%= render 'competitions/map', markers: @markers, competitions: @past_competitions %>
    </div>
  </div>

  <div class="bg-welcome">
    <div class="container padded-bottom padded-mini-top">
      <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2">
          <h2 class="text-center">Hall of Fame</h2>
          <div class="panel panel-default">
          <table class="table">
            <tbody>
              <% @hof_users.each do |user| %>
                  <tr>
                    <td>
                      <%= render 'users/avatar_medium', user: user %>
                    </td>
                    <td class="text-uppercase"><%= link_to user, user %></td>
                    <td>
                      <% user.competition_victories.each do |competition| %>
                        <%= link_to competition do %>
                          <span class="trophies"><i class="fa fa-trophy" data-toggle="tooltip" data-placement="bottom" title="<%= competition %>"></i></span>
                        <% end %>
                      <% end %>
                    </td>
                    <td>
                      <% user.track_victories.each do |track| %>
                        <%= link_to competition_path(id: track.competition_id, anchor: "track-#{track.id}-result") do %>
                          <span class="medals"><i class="icomoon icon-medal" data-toggle="tooltip" data-placement="bottom" title="<%= track %>"></i></span>
                        <% end %>
                      <% end %>
                    </td>
                    <td>
                      <% user.badges.each do |badge| %>
                        <%= image_tag badge.picture, class: "award", alt: "", data: { toggle: "tooltip", placement: "bottom"}, title: "#{ badge.description }" %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
                <tr>
                  <td colspan="5" class="bg-light-grey">
                    <%= link_to users_path do %>
                    <div class="text-center"><i class="fa fa-plus marged-micro-sides"></i> <%= t('.link_hall_of_fame') %></div>
                    <% end %>
                  </td>
                </tr>
            </tbody>
          </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/rules.en.html.erb
<%= content_for(:title) do %>
  Rules
<% end %>

<%= content_for(:description) do %>
  <%= t('welcome.index.intro') %>
<% end %>

<div class="container padded-mini rules">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
      <h1>Rules of the competition</h1>

      <ol type="A">
        <li>
          <strong>Conditions of participation</strong>
          <p>Those who are adults (18 years old) on the day of departure of the competition are permited to register</p>
        </li>
        <li>
          <strong>Rules of the race</strong>
          <ol>
            <li>Any violation of one of the following rules will result in disqualification of the team concerned.</li>
            <li>The race takes place in teams of 2. The members of each team are inseparable for the duration of the journey.</li>
            <li>A team can consist of two males or a female and a male.</li>
            <ol type="a">
              <li>Exception: If there are more females than males registred to a competition, a team can consist of 2 females on a volunteer basis (i.e. the 2 females must accept to be with another female). In that case, the organizer can decide of a handicap for the female-only team(s) as it is generally accepted that 2 girls are more likely to be taken for a ride.</li>
            </ol>
            <li>Teams and departure locations are drawn by the competition organizer. Team compositions, time and place of departure of the race, as well as the exact location of the finish line are communicated to the participants by the organizer between the end of the registrations and the start of the competition.</li>
            <li>The winning team will be that which will arrive first on the finish line. The team must be able to provide a photo of the two members on the finish line. The date of the photo serves as time of arrival.</li>
            <li>If two teams or more arrive at the same time on the finish line, they all will be attributed the same rank even if their photos are taken with a few seconds of difference.</li>
            <li>It is not allowed to spend money for transportation between the place of departure and the finish line. It is allowed to spend money on other goods (food, toilets, etc). It is not allowed to prepare a trip, ie asking an acquaintance in advance to driving a team from point A to point B.</li>
            <li>
              It is not allowed to hitchhike or to enter a car between 11pm and 7am.
              <ol type="a">
                <li>Exception: It is allowed to enter a car during this period if it is parked during the entire period.</li>
              </ol>
            </li>
            <li>
              In case of a journey beginning before 11pm and ending after 11pm, the team should pause for 8 consecutive hours after the end of the last journey.
              <ol type="a">
                <li>Example: a team gets into a car at 10pm and is dropped at 1am, it can resume hitchhiking at 9am.</li>
              </ol>
              In addition, the breaks made by the driver during this period count as journey, they can not be deducted from the 8 hours break.
              <ol type="a" start="2">
                <li>Example: a team is taken at 10pm, the driver drives until 1am, pauses until 1:30am then drives again and drops the team at 2am. The team can resume hitchhiking at 10am.</li>
                <li>Exception: If a team is dropped close to the finish between 11pm and 7am, it may decide to walk (but not to hitchhike) to the finish line. Their official arrival time will be increased by 8 hours. Example: A team is dropped at 1am and decides to walk. They arrive at 2:13am on the finish line. Their official finish time is 10:13am.</li>
              </ol>

            </li>
          </ol>
        </li>
        <li>
          <strong>Multistage competition</strong>
          <ol>
            <li>After each stage, participants collect a certain number of points. Participants are informed of the points scale by the organizer of the competition.</li>
            <li>The final winner is the participant who earned the most points throughout the competition.</li>
            <li>For each stage the teams change. They are drawn by the event organizer.</li>
          </ol>
        </li>
      </ol>
    </div>
  </div>
</div>

app/views/welcome/rules.fr.html.erb
<%= content_for(:title) do %>
  Règles
<% end %>

<%= content_for(:description) do %>
  <%= t('welcome.index.intro') %>
<% end %>

<div class="container padded-mini rules">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
      <h1>Règles de compétition</h1>

      <ol type="A">
        <li>
          <strong>Conditions de participation</strong>
          <p>Peuvent s’inscrire les personnes adultes au jour du départ de la compétition.</p>
        </li>
        <li>
          <strong>Règles de la course</strong>
          <ol>
            <li>Toute infraction à l'une des règles suivante entrainera la disqualification de l'équipe concernée.</li>
            <li>La course se déroule par équipe de 2. Les membres de chaque équipe sont inséparables pendant toute la durée du périple.</li>
            <li>Une équipe peut être constituée de deux garçons ou d'une fille et un garçon.</li>
            <ol type="a">
              <li>Exception: Si à la fin de la phase d'inscription d'une compétition il y a plus de filles que de garçons inscrits, une ou plusieurs équipes de 2 filles peu(ven)t être formée(s) sur une base volontaire (c.à.d. que les 2 filles doivent accepter d'être avec une autre fille). Si ce cas se présente, l'organisateur peut ajouter un handicap pour les équipes de 2 filles, étant donné qu'il est généralement accepté que 2 filles sont plus facilement prisent pour un trajet en stop.</li>
            </ol>
            <li>Les équipes et les lieux de départ sont tirés au sort par l'organisateur de la compétition. La composition des équipes, l’heure et le lieu de départ de la course, ainsi que le lieu exact de la ligne d’arrivée sont communiqués aux participants par l'organisateur entre la fin des inscriptions et le début de la compétition.</li>
            <li>L’équipe vainqueur d'une étape sera celle qui arrivera en premier sur la ligne d’arrivée. L’équipe doit pouvoir fournir une photo des deux membres sur la ligne d’arrivée. L’heure de la prise de la photo fait office de temps à l’arrivée.</li>
            <li>Si deux équipes arrivent en même temps sur la ligne d’arrivée, elles seront déclarées à égalité même si leurs photos sont prises avec quelques secondes de différence.</li>
            <li>Il n’est pas permis de dépenser de argent pour le transport entre le lieu de départ et la ligne d’arrivée. Il est permis de dépenser de l’argent pour d’autres biens (nourriture, toilettes, etc). Il n’est pas non plus permis de préparer un trajet, c’est à dire demander préalablement à une connaissance de conduire une équipe d’un point A à un point B.</li>
            <li>
              Il n’est pas permis de faire du stop ni d’entrer dans une voiture entre 23h et 7h du matin.
              <ol type="a">
                <li>Exception: Il est permis d’entrer dans une voiture pendant cette période si cette dernière est stationnée durant l’entièreté de la période.</li>
              </ol>
            </li>
            <li>
              En cas de trajet ayant débuté avant 23h et se terminant après 23h, l’équipe doit faire une pause de 8h consécutives à compter de l’heure de dépose du dernier trajet.
              <ol type="a">
                <li>Exemple : une équipe monte dans une voiture à 22h et se fait déposer à 1h du matin, elle ne peut reprendre le stop qu’à 9h.</li>
              </ol>
              De plus, les pauses effectuées par le chauffeur pendant cette période comptent comme trajet, elles ne peuvent être déduites des 8h de pause.
              <ol type="a" start="2">
                <li>Exemple : une équipe est prise à 22h, le chauffeur roule jusqu’à 1h, fait une pause jusqu’à 1h30 puis roule à nouveau et dépose l’équipe à 2h. L’équipe ne peut reprendre le stop qu’à 10h.</li>
                <li>Exception : Si une équipe se fait déposer proche de la ligne d’arrivée entre 23h et 7h, elle peut décider d’aller à pied (mais pas de faire du stop) jusqu’à l’arrivée. Son temps officiel d’arrivée sera augmenté de 8h. Exemple : une équipe se fait déposer à 1h et décide de marcher. Elle arrive à 2h13 à l’arrivée. Son temps officiel d’arrivée est 10h13.</li>
              </ol>

            </li>
          </ol>
        </li>
        <li>
          <strong>Compétitions à plusieurs étapes</strong>
          <ol>
            <li>À l'issue de chaque étape, les participants récoltent un certain nombre de points. Le barème des points est transmis aux participants par l'organisateur de la compétition.</li>
            <li>Le vainqueur final est le participant qui aura engrangé le plus de points durant toute la compétition.</li>
            <li>Lors de chaque étape, les équipes changent et sont tirées au sort par l'organisateur de l'évènement.</li>
          </ol>
        </li>
      </ol>
    </div>
  </div>
</div>

app/views/welcome/rules.html.erb
<%= content_for(:title) do %>
  Règles
<% end %>

<%= content_for(:description) do %>
  <%= t('welcome.index.intro') %>
<% end %>

<div class="container padded-mini rules">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
      <h1>Règles de compétition</h1>

      <ol type="A">
        <li>
          <strong>Conditions de participation</strong>
          <p>Peuvent s’inscrire les personnes adultes au jour du départ de la compétition.</p>
        </li>
        <li>
          <strong>Règles de la course</strong>
          <ol>
            <li>Toute infraction à l'une des règles suivante entrainera la disqualification de l'équipe concernée.</li>
            <li>La course se déroule par équipe de 2. Les membres de chaque équipe sont inséparables pendant toute la durée du périple.</li>
            <li>Une équipe peut être constituée de deux garçons ou d'une fille et un garçon.</li>
            <li>Les équipes et les lieux de départ sont tirés au sort par l'organisateur de la compétition. La composition des équipes, l’heure et le lieu de départ de la course, ainsi que le lieu exact de la ligne d’arrivée sont communiqués aux participants par l'organisateur entre la fin des inscriptions et le début de la compétition.</li>
            <li>L’équipe vainqueur d'une étape sera celle qui arrivera en premier sur la ligne d’arrivée. L’équipe doit pouvoir fournir une photo des deux membres sur la ligne d’arrivée. L’heure de la prise de la photo fait office de temps à l’arrivée.</li>
            <li>Si deux équipes arrivent en même temps sur la ligne d’arrivée, elles seront déclarées à égalité même si leurs photos sont prises avec quelques secondes de différence.</li>
            <li>Il n’est pas permis de dépenser de argent pour le transport entre le lieu de départ et la ligne d’arrivée. Il est permis de dépenser de l’argent pour d’autres biens (nourriture, toilettes, etc). Il n’est pas non plus permis de préparer un trajet, c’est à dire demander préalablement à une connaissance de conduire une équipe d’un point A à un point B.</li>
            <li>
              Il n’est pas permis de faire du stop ni d’entrer dans une voiture entre 23h et 7h du matin.
              <ol type="a">
                <li>Exception: Il est permis d’entrer dans une voiture pendant cette période si cette dernière est stationnée durant l’entièreté de la période.</li>
              </ol>
            </li>
            <li>
              En cas de trajet ayant débuté avant 23h et se terminant après 23h, l’équipe doit faire une pause de 8h consécutives à compter de l’heure de dépose du dernier trajet.
              <ol type="a">
                <li>Exemple : une équipe monte dans une voiture à 22h et se fait déposer à 1h du matin, elle ne peut reprendre le stop qu’à 9h.</li>
              </ol>
              De plus, les pauses effectuées par le chauffeur pendant cette période comptent comme trajet, elles ne peuvent être déduites des 8h de pause.
              <ol type="a" start="2">
                <li>Exemple : une équipe est prise à 22h, le chauffeur roule jusqu’à 1h, fait une pause jusqu’à 1h30 puis roule à nouveau et dépose l’équipe à 2h. L’équipe ne peut reprendre le stop qu’à 10h.</li>
                <li>Exception : Si une équipe se fait déposer proche de la ligne d’arrivée entre 23h et 7h, elle peut décider d’aller à pied (mais pas de faire du stop) jusqu’à l’arrivée. Son temps officiel d’arrivée sera augmenté de 8h. Exemple : une équipe se fait déposer à 1h et décide de marcher. Elle arrive à 2h13 à l’arrivée. Son temps officiel d’arrivée est 10h13.</li>
              </ol>

            </li>
          </ol>
        </li>
        <li>
          <strong>Compétitions à plusieurs étapes</strong>
          <ol>
            <li>À l'issue de chaque étape, les participants récoltent un certain nombre de points. Le barème des points est transmis aux participants par l'organisateur de la compétition.</li>
            <li>Le vainqueur final est le participant qui aura engrangé le plus de points durant toute la compétition.</li>
            <li>Lors de chaque étape, les équipes changent et sont tirées au sort par l'organisateur de l'évènement.</li>
          </ol>
        </li>
      </ol>
    </div>
  </div>
</div>