config/routes.rb
Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'users/registrations' }

  scope '(:locale)', locale: /fr|en/ do
    get 'welcome/index'
    get '/rules', to: 'welcome#rules'

    resources :users, only: [:index, :show, :edit, :update]
    resources :competitions do
      resources :tracks, only: [:destroy, :edit, :update]
      resources :subscriptions, only: [:new, :edit, :update, :create, :destroy]
      get 'event', to: 'competitions#event'
    end

    resources :notification_settings, only: [:update]

    %w( 404 422 500 ).each do |code|
      get code, to: "errors#show", code: code
    end

    root 'welcome#index'

    require "sidekiq/web"
    authenticate :user, lambda { |u| u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end

end

app/models/subscription.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: subscriptions
#
#  id             :integer          not null, primary key
#  user_id        :integer          not null
#  competition_id :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  status         :integer          default("pending"), not null
#
# Indexes
#
#  index_subscriptions_on_competition_id  (competition_id)
#  index_subscriptions_on_user_id         (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (competition_id => competitions.id)
#  fk_rails_...  (user_id => users.id)
#

class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :competition

  after_update :status_changed
  after_create :make_track_ranks, if: :accepted?
  before_destroy :destroy_ranks

  enum status: { pending: 0, accepted: 1, refused: 2 }

  def name
    "#{user.name} => #{competition.name}"
  end

  def to_s
    name
  end

  def points
    competition.t_ranks.where(user: user).map(&:points).reduce(:+)
  end

  def result
    competition.ranks.find_by(user: user).try(:result)
  end

  private

    def status_changed
      if changes["status"].try(:any?) && changes["status"].last == "accepted"
        make_track_ranks
      elsif changes["status"].try(:any?) && changes["status"].last != "accepted"
        destroy_ranks
      end
    end

    def make_track_ranks
      competition.tracks.each do |track|
        Rank.create!(user: user, race: track)
      end
    end

    def destroy_ranks
      Rank.where(user: user, race: competition).destroy_all

      competition.tracks.each do |track|
        Rank.where(user: user, race: track).destroy_all
      end
    end
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true
# == Schema Information
#
# Table name: subscriptions
#
#  id             :integer          not null, primary key
#  user_id        :integer          not null
#  competition_id :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  status         :integer          default("pending"), not null
#
# Indexes
#
#  index_subscriptions_on_competition_id  (competition_id)
#  index_subscriptions_on_user_id         (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (competition_id => competitions.id)
#  fk_rails_...  (user_id => users.id)
#

class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:edit, :update, :destroy]
  before_action :find_competition, only: [:new, :edit, :create, :update]

  # POST
  def new
    authorize Subscription

    @form = Subscription::Contract::Create.new(Subscription.new)
    @form.prepopulate_user!(user: current_user)
  end

  def edit
    authorize @subscription, :update?

    @form = Subscription::Contract::Update.new(@subscription)
  end

  def create
    operation = Subscription::Create.call(params.merge(current_user: current_user))

    @form = operation.form

    if @form.valid?
      respond_to do |format|
        format.html { redirect_to operation.model.competition, notice: t("subscriptions.create.notice") }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  def update
    operation = Subscription::Update.call(params.merge(current_user: current_user))

    @form = operation.form

    if @form.valid?
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    authorize @subscription

    competition = @subscription.competition

    if competition.author.notification_setting.as_author_cancelation
      UserMailer.as_author_cancelation(@subscription.user.id,
                                       competition.id,
                                       competition.author.id).deliver_later
    end

    @subscription.destroy

    redirect_to competition, notice: t("subscriptions.destroy.notice")
  end

  private

    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    def find_competition
      @competition = Competition.find(params[:competition_id])
    end

    def subscription_params
      params.require(:subscription).permit(:status, :rules, :phone_number, :whatsapp, :telegram, :signal)
    end
end

app/views/subscriptions/_edit.html.erb
<%= link_to edit_competition_subscription_path(competition, subscription), data: { toggle: "tooltip", placement: "bottom" }, title: t('process'), remote: true do %>
  <i class="fa fa-reply text-muted"></i>
<% end %>

<!-- MODAL -->
<% if user_signed_in? %>
  <div class="modal" id="modal-sub-<%= subscription.id %>" tabindex="-1" role="dialog" aria-labelledby="new_registration">
    <div class="modal-dialog" role="document">
      <div id="modal-content-sub-<%= subscription.id %>" class="modal-content">
        <%= render 'subscriptions/process', subscription: subscription, competition: competition, user: user %>
      </div>
    </div>
  </div>
<% end %>
<!-- END MODAL -->

app/views/subscriptions/_form.html.erb
<%= simple_form_for([competition, subscription], remote: true) do |f| %>
  <%= f.error_notification %>
  <%= f.input :status, as: :hidden, input_html: { value: competition.default_registration_status } %>

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="new_registration"><%= t('subscriptions.new.title', competition: competition.name) %></h4>
  </div>

  <div class="modal-body text-left">
    <div class="competition_details">
      <p><strong><%= t('activerecord.models.competition', count: 1).capitalize %></strong></p>
      <div class="row">
        <div class="col-xs-3 col-sm-2"><%= t('competitions.params.name') %>:</div>
        <div class="col-xs-9 col-sm-10"><%= competition %></div>
      </div>
      <div class="row">
        <div class="col-xs-3 col-sm-2"><%= t('competitions.route') %>:</div>
        <div class="col-xs-9 col-sm-10">
          <%= competition.route %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-3 col-sm-2"><%= t('competitions.dates') %>:</div>
        <div class="col-xs-9 col-sm-10"><%= date_format(competition.start_date) %> – <%= date_format(competition.end_date) %>
        </div>
      </div>
    </div>
    <div class="user_details padded-mini">
      <p>
        <strong><%= t('subscriptions.new.user_infos') %></strong>
        <% if policy(current_user).update? %>
          <small><%= link_to t('edit'), edit_user_path(current_user), target: "_blank" %></small>
        <% end %>
      </p>
      <div class="media">
        <div class="media-left">
          <%= render 'users/avatar_large', user: current_user %>
        </div>
        <div class="media-body">
          <%= f.simple_fields_for :user do |u| %>
            <p><i class="fa fa-user fa-fw"></i><%= current_user.name %></p>
            <p><i class="fa fa-envelope-o fa-fw"></i><%= current_user.email %></p>
            <p class="form-inline">
              <i class="fa fa-phone fa-fw"></i><%= t('subscriptions.new.phone_number') %>: <%= u.input_field :phone_number, as: :string, class: "form-control input-sm" %>
            </p>
            <p>
              <strong><%= t('subscriptions.new.messaging_apps') %>:</strong>
              <%= u.input :whatsapp, wrapper_html: {class: "checkbox-inline" } %>
              <%= u.input :telegram, wrapper_html: {class: "checkbox-inline" } %>
              <%= u.input :signal, wrapper_html: {class: "checkbox-inline" } %>
            </p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="tos">
      <%= f.input :rules, as: :boolean, label: t('subscriptions.params.rules_label_html', href: link_to(t('subscriptions.params.rules_href_text'), rules_path, target: "_blank")) %>

      <p class="text-uppercase small">
        <% if competition.default_registration_status == "accepted" %>
          <%= t('subscriptions.new.tos', competition: competition.name) %>
        <% else %>
          <%= t('subscriptions.new.pending_tos', competition: competition.name) %>
        <% end %>
      </p>
    </div>

  </div> <!-- END MODAL-BODY -->
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('cancel') %></button>
    <%= f.button :submit, t('competitions.apply'), class: "navbar-wagon-button btn", style: "margin: 20px 0;", data: {toggle: "modal", target: "#modal"} %>
  </div>
<% end %>

app/views/subscriptions/_new.html.erb
<div id="registration-area-<%= competition.id %>" class="text-center padded-mini-bottom">
  <% if !competition.finished? && competition.accepted_users.include?(current_user) %>
    <!-- case: applied, accepted -->
    <i class="fa fa-check text-success"></i> <%= t('subscriptions.accepted') %>

  <% elsif competition.pending_users.include?(current_user) %>
    <!-- case: applied, pending -->
    <i class="fa fa-refresh text-warning"></i> <%= t('subscriptions.pending') %>&nbsp;&nbsp;
    <%= link_to t('competitions.cancel'), competition_subscription_path(competition, Subscription.find_by(user: current_user, competition: competition)), method: :delete, data: { confirm: t('competitions.form.delete.message') } %>

  <% elsif competition.refused_users.include?(current_user) %>
    <!-- case: applied, refused -->
    <i class="fa fa-times text-danger"></i> <%= t('subscriptions.refused') %>

  <% else %>
    <% if policy(competition).apply? %>
      <!-- case: not applied or not signed in -->
      <%= link_to t('competitions.apply'), new_competition_subscription_path(competition), class: "navbar-wagon-button btn padded-mini-bottom", remote: user_signed_in? %>

      <!-- MODAL -->
      <% if user_signed_in? %>
        <div class="modal" id="modal-<%= competition.id %>" tabindex="-1" role="dialog" aria-labelledby="new_registration">
          <div class="modal-dialog" role="document">
            <div id="modal-content-<%= competition.id %>" class="modal-content">
              <% subscription = Subscription::Contract::Create.new(Subscription.new)
                 subscription.prepopulate!(user: current_user) %>
              <%= render 'subscriptions/form', competition: competition, subscription: subscription %>
            </div>
          </div>
        </div>
      <% end %>
      <!-- END MODAL -->
    <% end %>
  <% end %>
</div>

app/views/subscriptions/_process.html.erb
<%= simple_form_for([competition, subscription], remote: true) do |f| %>
  <%= f.error_notification %>

  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="new_registration"><%= t('subscriptions.edit.title', competition: competition.name, user: user.name) %></h4>
  </div>

  <div class="modal-body text-left">
    <div class="user_details padded-mini">
      <p>
        <strong><%= t('subscriptions.new.user_infos') %></strong>
      </p>
      <div class="media">
        <div class="media-left">
          <%= render 'users/avatar_large', user: user %>
        </div>
        <div class="media-body">
          <p><i class="fa fa-user fa-fw"></i><%= user.name %></p>
          <p><i class="fa fa-envelope-o fa-fw"></i><%= user.email %></p>
        </div>
      </div>
      <div class="text-center padded-mini">
        <%= f.collection_radio_buttons :status, [["pending", "refresh text-warning"], ["accepted", "check text-success"], ["refused", "times text-danger"]], :first, :last, checked: subscription.status do |b| %>
          <% b.label(class: "marged-micro-sides") {"<span class='marged-micro-sides'><i class='fa fa-#{ b.text }'></i> #{t("subscriptions.#{b.value}_short")}</span><div>#{b.radio_button}</div>".html_safe } %>
        <% end %>
      </div>
    </div>

  </div> <!-- END MODAL-BODY -->
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('cancel') %></button>
    <%= f.button :submit, t('subscriptions.edit.button'), class: "navbar-wagon-button btn", style: "margin: 20px 0;", data: {toggle: "modal", target: "#modal"} %>
  </div>
<% end %>

app/views/subscriptions/_user_registred.html.erb
<div class="flex-item">
  <%= render 'users/avatar_medium', user: user %>
</div>
<div class="flex-item-fill">
  <div>
    <%= link_to user.name, user %>
  </div>
  <div>
    <%= user.email %> <%= mail_to user.email do %><i class="fa fa-envelope-o"></i><% end %>
  </div>
  <div>
    <%= user.phone_number %> <% if user.whatsapp %><i class="fa fa-whatsapp fa-fw text-success cursor-default" data-toggle="tooltip" data-placement="bottom" title="whatsapp"></i><% end %> <% if user.telegram %><i class="fa fa-paper-plane-o fa-fw text-success cursor-default"  data-toggle="tooltip" data-placement="bottom" title="telegram"></i><% end %>
    <% if user.signal %><i class="fa fa-comment-o fa-fw text-success cursor-default"  data-toggle="tooltip" data-placement="bottom" title="signal"></i><% end %>
  </div>
</div>

app/views/subscriptions/create.js.erb
<% if @form.errors.any? %>
  // Render new review form with errors
  $("#modal-content-<%= @competition.id %>").html("<%= j render 'subscriptions/form', competition: @competition, subscription: @form %>");
<% else %>
  $("#modal-<%= @competition.id %>").modal('hide');

  $("#competition-<%= @competition.id %>-dynamic").html("<%= j render 'competitions/dynamic', competition: @competition %>")
  $('[data-toggle="tooltip"]').tooltip();

  $("#alerts-bar").html('<div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= t("subscriptions.create.notice") %></div>').hide();
  $("#alerts-bar").slideDown();
<% end %>

app/views/subscriptions/edit.html.erb
<%= content_for(:title) do %>
  <%= @competition %> | <%= @form.user %>
<% end %>

<%= content_for(:description) do %>
  Traitement de l'inscription de <%= @form.user %> à <%= @competition %>. <%= t('welcome.index.intro') %>
<% end %>

<div class="container padded-mini">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
      <div class="panel panel-default">
        <%= render 'process', subscription: @form, competition: @competition, user: @form.user %>
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/edit.js.erb
$("#modal-sub-<%= @subscription.id %>").modal('show');

app/views/subscriptions/new.html.erb
<%= content_for(:title) do %>
  <%= @competition %> | Inscription
<% end %>

<%= content_for(:description) do %>
  Inscription à <%= @competition %>. <%= t('welcome.index.intro') %>
<% end %>

<div class="container padded-mini">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">
      <div class="panel panel-default">
        <%= render 'subscriptions/form', competition: @competition, subscription: @form %>
      </div>
    </div>
  </div>
</div>

app/views/subscriptions/new.js.erb
$("#modal-<%= @competition.id %>").modal('show');

app/views/subscriptions/update.js.erb
<% if @form.errors.any? %>
  // Render new review form with errors
  $("#modal-content-sub-<%= @form.id %>").html("<%= j render 'subscriptions/process', subscription: @form, competition: @competition, user: @form.user %>");
<% else %>
  $("#modal-sub-<%= @form.id %>").modal('hide');

  <%# Dashboard of creator: update number of pending %>
  <% if current_user.pending_registrations_for_creations > 0 %>
    $('.registrations-alert').html("<%= current_user.pending_registrations_for_creations %>");
  <% else %>
    $('.registrations-alert').hide();
  <% end %>

  <% if @form.status == "accepted" %>
    $("#competition-<%= @competition.id %>-dynamic").html("<%= j render 'competitions/dynamic', competition: @competition %>")

    $("#subscription-<%= @form.id %>-pending").remove();
    $("#competition-<%= @competition.id%>-accepted").append("<%= j render 'competitions/accepted_user', user: @form.user %>")

    <%# reload tooltip because bootstrap %>
    $('[data-toggle="tooltip"]').tooltip();
  <% elsif @form.status == "refused" %>
    $("#competition-<%= @competition.id %>-dynamic").html("<%= j render 'competitions/dynamic', competition: @competition %>")

    $("#subscription-<%= @form.id %>-pending").remove();
    $("#competition-<%= @competition.id%>-refused").append("<%= j render 'competitions/refused_user', user: @form.user %>")

    <%# reload tooltip because bootstrap %>
    $('[data-toggle="tooltip"]').tooltip();
  <% end %>
<% end %>